version: '2'
services:
  sensor:
    build: movment/.
    image: ollebo/rpi-sensor:v0.2
    environment:
      - URL=https://iot.home.ollebo.com/data/
      - API_KEY=1234
      - ID=1234
      - HOSTNAME=localhost
      - CLIENT=docker
      - DEVICE_ID=local
      - SLEEP=50
      - ACTIONFILE=/vstech/status/go
    volumes:
      - ./:/code
      - /sys:/sys
      - /opt/data:/vstech/data
    command: python3 LPS22HB.py
    privileged: true
  ads1050:
    build: movment/.
    image: ollebo/rpi-sensor:v0.2
    environment:
      - URL=https://iot.home.ollebo.com/data/
      - API_KEY=1234
      - ID=1234
      - HOSTNAME=localhost
      - CLIENT=docker
      - DEVICE_ID=local
      - SLEEP=50
      - ACTIONFILE=/vstech/status/go
    volumes:
      - ./:/code
      - /sys:/sys
      - /opt/data:/vstech/data
    command: python3 ads1015.py
    privileged: true
  ICM20948:
    build: movment/.
    image: ollebo/rpi-sensor:v0.2
    environment:
      - URL=https://iot.home.ollebo.com/data/
      - API_KEY=1234
      - ID=1234
      - HOSTNAME=localhost
      - CLIENT=docker
      - DEVICE_ID=local
      - SLEEP=50
      - ACTIONFILE=/vstech/status/go
    volumes:
      - ./:/code
      - /sys:/sys
      - /opt/data:/vstech/data
    command: python3 ICM20948.py
    privileged: true
  gps:
    build: gps/.
    image: ollebo/rpi-gps:v0.2
    environment:
      - URL=https://iot.home.ollebo.com/data/
      - API_KEY=1234
      - ID=1234
      - HOSTNAME=localhost
      - CLIENT=docker
      - DEVICE_ID=local
      - SLEEP=50
      - ACTIONFILE=/vstech/status/go
    volumes:
      - ./:/code
      - /opt/data:/vstech/data
    #command: tail -f /etc/fstab
    network_mode: host
  camera:
    build: camera/.
    image: ollebo/rpi-camera:v0.2
    environment:
      - URL=https://iot.home.ollebo.com/data/
      - API_KEY=1234
      - ID=1234
      - HOSTNAME=localhost
      - CLIENT=docker
      - DEVICE_ID=local
      - LD_LIBRARY_PATH=/opt/vc/lib/
      - SLEEP=50
      - ACTIONFILE=/ollebo/data/status/go
    volumes:
      - ./:/code
      - /dev:/dev
      - /sys:/sys
      - /opt/vc:/opt/vc
      - /opt/data:/ollebo/data
      - /opt/images:/ollebo/images
    #command: tail -f /etc/fstab
    privileged: true
  navio:
    build: navio2/.
    image: ollebo/navio:v0.1
    environment:
      - URL=https://iot.home.ollebo.com/data/
      - API_KEY=1234
      - ID=1234
      - HOSTNAME=localhost
      - CLIENT=docker
      - DEVICE_ID=local
      - LD_LIBRARY_PATH=/opt/vc/lib/
      - SLEEP=50
      - ACTIONFILE=/ollebo/status/go
    volumes:
      - ./navio2:/code
      - /dev:/dev
      - /sys:/sys
      - /opt/data:/ollebo/data
      - /opt/images:/ollebo/images
    #command: tail -f /etc/fstab
    privileged: true