version: '2'
services:
  gps:
    image: ollebo/navio:v0.1
    environment:
      - URL=https://iot.home.ollebo.com/data/
      - API_KEY=1234
      - ID=1234
      - HOSTNAME=localhost
      - CLIENT=docker
      - DEVICE_ID=local
      - LD_LIBRARY_PATH=/opt/vc/lib/
      - SLEEP=50
      - ACTIONFILE=/ollebo/data/status/go
    volumes:
      - ./navio2:/code
      - /dev:/dev
      - /sys:/sys
      - /opt/data:/ollebo/data
      - /opt/images:/ollebo/images
    command: python3 GPS.py
    privileged: true
  gyro:
    image: ollebo/navio:v0.1
    environment:
      - URL=https://iot.home.ollebo.com/data/
      - API_KEY=1234
      - ID=1234
      - HOSTNAME=localhost
      - CLIENT=docker
      - DEVICE_ID=local
      - LD_LIBRARY_PATH=/opt/vc/lib/
      - SLEEP=5
      - ACTIONFILE=/ollebo/data/status/go
    volumes:
      - ./navio2:/code
      - /dev:/dev
      - /sys:/sys
      - /opt/data:/ollebo/data
      - /opt/images:/ollebo/images
    command: python3 AccelGyroMag.py
    depends_on:
      - gps
    privileged: true
