version: '2'
services:
  gps:
    image: ollebo/rpi-gps:v0.2
    environment:
      - URL=https://iot.home.ollebo.com/data/
      - API_KEY=1234
      - ID=1234
      - HOSTNAME=localhost
      - CLIENT=docker
      - DEVICE_ID=local
      - SLEEP=50
      - ACTIONFILE=/vstech/status/go
    volumes:
      - ./:/code
      - /opt/data:/vstech/data
    #command: tail -f /etc/fstab
    network_mode: host
  camera:
    image: ollebo/rpi-camera:v0.2
    environment:
      - URL=https://iot.home.ollebo.com/data/
      - API_KEY=1234
      - ID=1234
      - HOSTNAME=localhost
      - CLIENT=docker
      - DEVICE_ID=local
      - LD_LIBRARY_PATH=/opt/vc/lib/
      - SLEEP=50
      - ACTIONFILE=/vstech/status/go
    volumes:
      - ./:/code
      - /dev:/dev
      - /sys:/sys
      - /opt/vc:/opt/vc
      - /opt/data:/vstech/data
      - /opt/images:/vstech/images
    #command: tail -f /etc/fstab
    privileged: true
