
apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send-api
  template:
    metadata:
      labels:
        app: send-api
    spec:
      containers:
        - image: ollebo/rpi-sensor:v0.2
          imagePullPolicy: Always
          name: send-api
          command: ["python3","-u","sendToApi.py"]
          env:
            - name: URL
              value: https://vstech-se.vstech.io/data/
            - name: API_KEY
              value: "hsydhasdhjkasdas"
            - name: ID
              value: "hrb"
            - name: HOSTNAME
              value: localhost
            - name: CLIENT
              value: k8s
            - name: DEVICE_ID
              value: local
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          #livenessProbe:
          # httpGet:
          #   path: 
          #   port: 8000
          #   httpHeaders:
          #   - name: X-Custom-Header
          #     value: Awesome
          # initialDelaySeconds: 3
          # periodSeconds: 3
          #readinessProbe:
          # httpGet:
          #   path: /healthz/index.html
          #   port: 8000
          #   httpHeaders:
          #   - name: X-Custom-Header
          #     value: Awesome
          # initialDelaySeconds: 3
          # periodSeconds: 3
