
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-sensor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpi-sensor
  template:
    metadata:
      labels:
        app: rpi-sensor
    spec:
      containers:
        - image: ollebo/rpi-sensor
          imagePullPolicy: Always
          name: rpi-sensor
          command: ["python3","-u","ICM20948.py"]
          volumeMounts:
            - name: sys
              mountPath: /sys
          env:
            - name: URL
              value: https://iot.home.ollebo.com/data/
            - name: API_KEY
              value: "1234"
            - name: ID
              value: "1234"
            - name: HOSTNAME
              value: localhost
            - name: CLIENT
              value: k8s
            - name: DEVICE_ID
              value: local
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"
        - image: ollebo/rpi-sensor
          imagePullPolicy: Always
          name: rpi-temp
          command: ["python3","-u","LPS22HB.py"]
          volumeMounts:
            - name: sys
              mountPath: /sys
          env:
            - name: URL
              value: https://iot.home.ollebo.com/data/
            - name: API_KEY
              value: "1234"
            - name: ID
              value: "1234"
            - name: HOSTNAME
              value: localhost
            - name: CLIENT
              value: k8s
            - name: DEVICE_ID
              value: local
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"
      volumes:
        - name: sys
          hostPath:
            path: /sys
          #livenessProbe:
          # httpGet:
          #   path: 
          #   port: 8000
          #   httpHeaders:
          #   - name: X-Custom-Header
          #     value: Awesome
          # initialDelaySeconds: 3
          # periodSeconds: 3
          #readinessProbe:
          # httpGet:
          #   path: /healthz/index.html
          #   port: 8000
          #   httpHeaders:
          #   - name: X-Custom-Header
          #     value: Awesome
          # initialDelaySeconds: 3
          # periodSeconds: 3

